export const projects = [
  { id: 'responsive-fe-design', title: 'The first website', category: 'Foundations', description: 'Where it started. A personal site, a counter, and a handful of JavaScript experiments.', root: 'responsive-fe-design', entry: 'index.html', color: '#cdd5f1', mark: '01', pages: [['Home', 'index.html'], ['Counter', 'learnmoreno.html'], ['Blackjack', 'blackjack.html'], ['Incident watch', 'warning.html'], ['Password generator', 'password-generator.html']] },
  { id: 'unit-converter', title: 'Unit converter', category: 'JavaScript', description: 'Meters to feet, liters to gallons, and a little everyday math.', root: 'unit-converter', entry: 'index.html', color: '#e2d6fa', mark: '02' },
  { id: 'restaurant-app', title: 'Matt’s diner', category: 'JavaScript', description: 'Burgers, pizza, and an interactive menu. Build an order and try the checkout.', root: 'restaurant-app', entry: 'index.html', color: '#f3d4b6', mark: '03' },
  { id: 'tindog', title: 'Tindog', category: 'JavaScript', description: 'A familiar swipe, with much better company. Meet Rex, Bella, and Teddy.', root: 'tindog', entry: 'index.html', color: '#f2c9d5', mark: '04' },
  { id: 'color-generator', title: 'Color scheme generator', category: 'JavaScript', description: 'An early exploration of a palette picker and color schemes.', root: 'color-generator', entry: 'index.html', color: '#c3dfc9', mark: '05', note: 'This exercise is unfinished in the original files; its placeholder controls are preserved.' },
  { id: 'movie-watchlist', title: 'Movie watchlist', category: 'JavaScript', description: 'Find a film and save something for later. A first outing with a movie API.', root: 'movie-watchlist', entry: 'index.html', color: '#d5d2c9', mark: '06', pages: [['Find a film', 'index.html'], ['My watchlist', 'watchlist.html']], note: 'Movie search uses the original external API. Its availability and old API key may affect results.' },
  { id: 'learning-journal', title: 'Learning journal', category: 'Foundations', description: 'Notes from the beginning, brought together in a responsive blog layout.', root: 'learning-journal', entry: 'html/learningjournal.html', color: '#cbdcdb', mark: '07' },
  { id: 'digital-business-card', title: 'Digital business card', category: 'React', description: 'A small introduction to me, and an introduction to building with React.', root: 'digital-business-card/vite-project', entry: 'index.html', color: '#d5cbe2', mark: '08', react: true },
  { id: 'travel-journal', title: 'Travel journal', category: 'React', description: 'Places worth remembering, collected into reusable React components.', root: 'travel-journal/vite-project', entry: 'index.html', color: '#f0c9c3', mark: '09', react: true, note: 'Some original travel photos come from external image services and may no longer load.' },
];
